# Generated by Django 3.2 on 2022-11-14 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerapp', '0002_auto_20221114_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 14, 19, 38, 49, 868788), verbose_name='datetime'),
        ),
    ]
